# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d176255bad68744e7e6137dc639eb8e7aaa7883bc6e158fb8e7626b985c698e92df12cdaf5fd1d8251822cd4a2ef7c99696ff05ec731ac4b1b36ede06ed7cee4

test:
  secret_key_base: 3be34e37a18f5ae33e04b143f0d416c272e41813a37916aa5ae36d23d7ff4bc406676275e6141b91fe8c5a3ccef1efb7323f62ac09210b380a9de283307096b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
